src/sf/src/main/default/objects/CashSchedulerServerSettings__c/CashSchedulerServerSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Cash Scheduler Server Settings</label>
</CustomObject>

src/sf/src/main/default/objects/CashSchedulerServerSettings__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

src/sf/src/main/default/objects/CashSchedulerServerSettings__c/fields/SecurityToken__c.field-meta.xml
<CustomField>
    <fullName>SecurityToken__c</fullName>
    <label>Security Token</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sf/src/main/default/objects/Contact/fields/CashSchedulerId__c.field-meta.xml
<CustomField>
    <fullName>CashSchedulerId__c</fullName>
    <externalId>true</externalId>
    <label>Cash Scheduler Id</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

src/sf/src/main/default/objects/Wallet__c/Wallet__c.object-meta.xml
<CustomObject>
    <label>Wallet</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wallets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/sf/src/main/default/objects/Wallet__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Balance</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/sf/src/main/default/objects/Wallet__c/fields/CurrencyName__c.field-meta.xml
<CustomField>
    <fullName>CurrencyName__c</fullName>
    <defaultValue>&quot;USD&quot;</defaultValue>
    <label>Currency Name</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/sf/src/main/default/objects/Wallet__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Default</label>
    <type>Checkbox</type>
</CustomField>

src/sf/src/main/default/objects/Wallet__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>User</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Wallets</relationshipLabel>
    <relationshipName>Wallets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/sf/src/main/default/classes/data/TestDataFactory.cls
/**
 * Created by Ilya Matsuev on 3/18/2021.
 */

public with sharing class TestDataFactory {

    public static final String CASH_SCHEDULER_SERVER_ENDPOINT = 'https://cash-scheduler-test.com/test';
    public static final String CASH_SCHEDULER_SERVER_SECURITY_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';


    public CashSchedulerServerSettings__c generateDefaultServerSettings() {
        return new CashSchedulerServerSettings__c(
                SetupOwnerId = UserInfo.getOrganizationId(),
                Endpoint__c = CASH_SCHEDULER_SERVER_ENDPOINT,
                SecurityToken__c = CASH_SCHEDULER_SERVER_SECURITY_TOKEN
        );
    }

    public Account generateCashSchedulerAccount() {
        return new Account(
                Name = Label.CashSchedulerAccountName,
                Industry = 'Technology',
                Type = 'Customer - Direct',
                Website = 'http://localhost:3000/'
        );
    }

    public Contact generateContact(
            Id accountId,
            Integer externalId,
            String firstName,
            String lastName,
            String email
    ) {
        return new Contact(
                AccountId = accountId,
                CashSchedulerId__c = externalId,
                FirstName = firstName,
                LastName = lastName,
                Email = email
        );
    }

    public Case generateCaseWithoutContact(
            String name,
            String email,
            String subject
    ) {
        return new Case(
                SuppliedName = name,
                SuppliedEmail = email,
                Subject = subject,
                Description = subject
        );
    }

    public Wallet__c generateWallet(
            Id contactId,
            Integer externalId,
            String name,
            Decimal balance,
            String currencyName,
            Boolean isDefault
    ) {
        return new Wallet__c(
                User__c = contactId,
                CashSchedulerId__c = externalId,
                Name = name,
                Balance__c = balance,
                CurrencyName__c = currencyName,
                IsDefault__c = isDefault
        );
    }
}